### ISSUE TITLE
update to 1.17.1

### ISSUE THREAD

**Issue by alex110220021** [scomans/MyPet#1483] opened 2021-08-06 09:21 UTC
# Question about MyPet
hi, can you update MyPet Plugin to 1.17.1?
my server on version 1.17.1 and i can't use your plugin.

**Comment by CJBlakey** [comment] 2021-08-06 10:06
https://github.com/scomans/MyPet/issues/1478#issue-922497887 Duplicate of.

just follow the other issue rather than raising new ones and spamming the developers.

**Closed** 2021-08-06 13:06 UTC
Labels: Question
